site_name: Risco e Ficha de Controle de Carga
site_description: Análise de risco e controle de fluxo de procedimentos em cargas

nav:
    - Home: index.md
    - Mídia: media.md
    - "Funcionalidades":
          - "Interface de administração":
            - "Admin - tabelas": admin/admin.md
            - "Roteiros - \"Check-lists\"": admin/roteiros.md
            - "Gerenciamento de Usuários e Perfis": admin/usuarios.md
            - "Modelo de permissão": admin/permissoes.md
    - "Novidades":
        - "Interface Telegram - 16/Junho/2020": novidades/20200616.md
        - "Tela 'Consulta de Empresa', Campo Empresa e Base Laudos - 03/Junho/2020": novidades/20200603.md
        - "Tela 'Consulta de Contêiner' - 12/Maio/2020": novidades/20200512.md
        - "Função 'novas/não vistas' - 7/Maio/2020": novidades/20200507b.md
        - "Melhorias em Minhas Fichas - 7/Maio/2020": novidades/20200507.md
        - "Programação de verificação física - 1/Maio/2020": novidades/20200501.md
    - "Roteiro de uso da ficha de controle - fluxo de importação":
        - "Introdução": exemplos/inicio.md
        - "Cadastrando ficha e programando verificação - Equipe 221B": exemplos/221ba.md
        - "Preenchendo a verificação física - Equipe 221B": exemplos/221bb.md
        - "Analisando a primeira parte - Equipe 221b": exemplos/221bc.md
        - "Solicitando Laudos - Equipe 221b": exemplos/221bd.md
        - "Saneamento, auto, RFFP - Equipe 221b": exemplos/221be.md
        - "Analise geral da Divisão": exemplos/221bf.md
        - "Resumo do roteiro (parte 1 - 221b)": exemplos/roteiro1completo.md
        - "Cadastrando ficha - Equipe SY": exemplos/SYa.md
        - "Verificação física, Intimação, Saneamento - Equipe SY": exemplos/SYb.md
        - "Auto, RFFP, check-list - Equipe SY": exemplos/SYc.md
        - "Analise geral da Divisão": exemplos/SYd.md
        - "Resumo do roteiro (parte 2 - SY)": exemplos/roteiro2completo.md




theme:
  name: 'material'
  language: 'pt'
#  palette:
#    primary: 'indigo'
#    accent: 'Green'
  logo: 'images/material_logo.svg'

