site_name: Risco e Ficha de Controle de Carga
site_description: Análise de risco e controle de fluxo de procedimentos em cargas

nav:
    - Home: index.md
    - Mídia: media.md
    - "Funcionalidades":
          - "Interface de administração":
            - "Admin - tabelas": admin/admin.md
            - "Roteiros - \"Check-lists\"": admin/roteiros.md
            - "Gerenciamento de Usuários e Perfis": admin/usuarios.md
            - "Modelo de permissão": admin/permissoes.md
          - "Pesquisando Fichas":
            - "Fichas de Carga": pesquisas/pesquisa.md
            - "Minhas Fichas": pesquisas/minhasfichas.md
            - "Kanban": pesquisas/kanban.md
            - "Pesquisas rápidas e integradas": pesquisas/rapida.md
    - "Roteiro de uso da ficha de controle - mercadoria abandonada":
        - "Verificação física, registro do TG e lavratura do Auto": exemplos/mercadoria_abandonada/MAa.md
        - "Solicitando e recebendo a manifestação de órgão anuente": exemplos/mercadoria_abandonada/MAb.md
        - "Direcionando a ficha após resposta do órgão anuente": exemplos/mercadoria_abandonada/MAc.md
        - "Recebimento de pedido de retomada de despacho": exemplos/mercadoria_abandonada/MAd.md
        - "Roteiro GMAB AJNA": exemplos/mercadoria_abandonada/MAe.md
    - "Roteiro de uso na exportação":
        - "Roteiro geral": roteiro_exportacao/resumo.md
    - "Roteiro de uso na importação":
        - "Roteiro geral": roteiro_importacao/resumo.md
    - "Novidades":
        - "Painel de OKRs - 25/09/2020": novidades/20200925.md
        - "Função 'Informar Apreensão sem Termo de Guarda' - 17/09/2020": novidades/20200917.md
        - "Interface Telegram - 16/Junho/2020": novidades/20200616.md
        - "Tela 'Consulta de Empresa', Campo Empresa e Base Laudos - 03/Junho/2020": novidades/20200603.md
        - "Tela 'Consulta de Contêiner' - 12/Maio/2020": novidades/20200512.md
        - "Função 'novas/não vistas' - 7/Maio/2020": novidades/20200507b.md
        - "Melhorias em Minhas Fichas - 7/Maio/2020": novidades/20200507.md
        - "Programação de verificação física - 1/Maio/2020": novidades/20200501.md
    - "Exemplos de uso - Scotland Yard":
        - "Introdução": exemplos/fluxo_importacao/inicio.md
        - "Cadastrando ficha e programando verificação - Equipe 221B": exemplos/fluxo_importacao/221ba.md
        - "Preenchendo a verificação física - Equipe 221B": exemplos/fluxo_importacao/221bb.md
        - "Analisando a primeira parte - Equipe 221b": exemplos/fluxo_importacao/221bc.md
        - "Solicitando Laudos - Equipe 221b": exemplos/fluxo_importacao/221bd.md
        - "Saneamento, auto, RFFP - Equipe 221b": exemplos/fluxo_importacao/221be.md
        - "Analise geral da Divisão": exemplos/fluxo_importacao/221bf.md
        - "Resumo do roteiro (parte 1 - 221b)": exemplos/fluxo_importacao/roteiro1completo.md
        - "Cadastrando ficha - Equipe SY": exemplos/fluxo_importacao/SYa.md
        - "Verificação física, Intimação, Saneamento - Equipe SY": exemplos/fluxo_importacao/SYb.md
        - "Auto, RFFP, check-list - Equipe SY": exemplos/fluxo_importacao/SYc.md
        - "Analise geral da Divisão": exemplos/fluxo_importacao/SYd.md
        - "Resumo do roteiro (parte 2 - SY)": exemplos/fluxo_importacao/roteiro2completo.md
    - "Roteiro de uso dos Relatórios Gerenciais":
        - "Relatórios Gerenciais - Introdução": exemplos/relatorios_gerenciais/RLa.md
        - "1 - Contagem de Eventos Especiais (Produtividade)": exemplos/relatorios_gerenciais/RLb.md
        - "2 - Pendências – Intimações": exemplos/relatorios_gerenciais/RLc.md
        - "3 - Pendências – Laudos Diversos (marca e assistente)": exemplos/relatorios_gerenciais/RLd.md
        - "4 - Pendências – Manifestação de anuentes": exemplos/relatorios_gerenciais/RLe.md
        - "5 - Pendências – Saneamentos pendentes / realizados": exemplos/relatorios_gerenciais/RLf.md
        - "6 - Relação de apreensão sem TG por Ano, mês e Setor": exemplos/relatorios_gerenciais/RLg.md
        - "7 - Relação de Fichas e Tgs por Ano, Mês e Setor": exemplos/relatorios_gerenciais/RLh.md
        - "8 - Relação de Verificações sem Ficha por Ano e Mês": exemplos/relatorios_gerenciais/RLi.md
        - "9 - Resumo das Verificações Físicas por Ficha por Setor": exemplos/relatorios_gerenciais/RLj.md
        - "10 - Resumo dos Tgs por Ficha por Setor": exemplos/relatorios_gerenciais/RLk.md
        - "11 - Visão de apreensões sem TG": exemplos/relatorios_gerenciais/RLl.md
        - "12 - Visão Geral Gerencial das Fichas por Setor": exemplos/relatorios_gerenciais/RLm.md
    - "Painel de OKRs":
        - "Como configurar": exemplos/painel_de_okrs/OKRa.md
        - "Exemplos": exemplos/painel_de_okrs/OKRb.md



theme:
  name: 'material'
  language: 'pt'
#  palette:
#    primary: 'indigo'
#    accent: 'Green'
  logo: 'images/material_logo.svg'

